# Variables of template's `site.*` scope
title: Fintech English

# Articles
collections:
  docs:
    title: Blogs
    order: 1
    output: true

# Jekyll Folders
# source: ./themes/km/
baseurl: /fintech-english
collections_dir: ./collections
layouts_dir: ./themes/km/layout
includes_dir: ./themes/km/layout
sass:
  sass_dir: ./themes/km/css
  style: compressed
# Jekyll Settings
defaults:
  -
    scope:
      path: ''
    values:
      layout: default
